[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bmp-scenario-sim"
version = "0.1.0"
description = "Watershed-scale BMP scenario simulator"
readme = "readme.md"
dynamic = ["dependencies"]
license = {file = "license.md"}
requires-python = ">=3.10"
authors = [
  { name = "USEPA" }
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
